@startuml
skinparam classAttributeIconSize 0
hide empty members
hide circle

interface AuthenticationMethod {
   + getName(): string
   + getTitle(): string
   + getHtmlFormBody(): string
   + start(callback: AuthenticationCallback, parameters: ValueProvider): boolean
   + update(callback: AuthenticationCallback): boolean
}

note as Note1
The user of WebAuthenticationSystem calls handleRequest() for each request
as long as no user has been logged in. Log-In is notified via the callback.
The  
end note

class WebAuthenticationSystem {
   - context: WebAppContext
   - callback: AuthenticationCallback
   + addMethod(method: AuthenticationMethod)
   + handleRequest()
}

class OpenIdAuthenticationMethod {

}

class CrestAuthenticationMethod {

}

interface AuthenticationCallback {
   + onUserAuthenticated(userName: string, userTag: string)
}

AuthenticationMethod <-up- DummyAuthenticationMethod
AuthenticationMethod <-up- OpenIdAuthenticationMethod
AuthenticationMethod <-up- CrestAuthenticationMethod

@enduml
