@startuml
skinparam classAttributeIconSize 0
hide empty members
hide circle

package dataModel {

interface DataModelProvider {
   + isModelExisting(name: string): boolean
   + createDataModel(name: string)

   + getWriteContext(name: string, userId: UUID): WriteContext
   + getReadContext(name: string, userId: UUID): ReadContext
}

class DataEntryId {
   - entryType: string
   - key: UUID
   + equals(other: DataEntryId): boolean
}

package writing {

interface WriteContext {
   + start(): WriteAccess
   + stop()
   + cancel()
}

DataModelProvider -down-> WriteContext

interface WriteAccess {
   + getNextInstanceValue(): int
   
   + retrieveDataEntry(entryId: DataEntryId): DataEntry
   + findDataEntries(entryType: string, contextId: DataEntryId, filter: map): DataEntry[]
   + createDataEntry(entryId: DataEntryId, data: map, contextId: DataEntryId)
   + updateDataEntry(entryId: DataEntryId, data: map)
   + deleteDataEntry(entryId: DataEntryId)

   + isAccessGranted(entries: DataEntryId[]): boolean
   + isControlGranted(entries: DataEntryId[]): boolean
   
   + addHistoryEntry(message: string, contextId: DataEntryId): int
}

WriteContext --> WriteAccess

}

package reading {

DataModelProvider -down-> ReadContext

interface ReadContext {
   + prepare()
   + unprepare()
   
   + readHistoryEntries(lastInstance: int, reader: HistoryReader) 
}

ReadContext -- HistoryReader
HistoryReader --> ReadAccess
ReadAccess -- DataModelReader

interface ReadAccess {
   + getCurrentInstanceId()
   + isAccessGranted(entryId: DataEntryId, entryInstance: int): boolean
   + readDataModel(reader: DataModelReader)
}

interface HistoryReader {
   + reset(access: ReadAccess)
   + receive(access: ReadAccess, entryInstance: int, message: string, contextId: DataEntryId)
}

interface DataModelReader {
   + receieDataEntry(entry: DataEntry)
}

}
}

package database {
class DatabaseDataContext {
   - transactionControl
   - statementExecutorFactory
   - tableNames: string[]
   - modelId: UUID
   + getModelId(): UUID
   + startTransaction(forWrite: boolean): int
   + commitTransaction()
   + rollbackTransaction()
   + getStatementExecutor(query: Query): StatementExecutor
   + readCurrentInterest(fromInstance: int)
   + isAccessGranted(interestId: DataEntryId, instance: int): boolean
   + isControlGranted(interestId: DataEntryId, instance: int): boolean
}

class DatabaseWriteContext {
   - dataContext: DatabaseDataContext
   - newInstance: int
   - historyInsertQuery: InsertQuery
   - historyInsertExecutor: StatementExecutor
}


class DatabaseReadContext {
   - dataContext: DatabaseDataContext
   - historySelectQuery: SelectQuery
   - historySelectExecutor: StatementExecutor
}

class DatabaseDataModelProvider {
   - transactionControl
   - statementExecutorFactory
   - tableNames: string[]
}


DatabaseDataModelProvider -left-> DatabaseWriteContext
DatabaseDataModelProvider -right-> DatabaseReadContext

DatabaseWriteContext *-down-> DatabaseDataContext
DatabaseReadContext *-down-> DatabaseDataContext
}

@enduml
