@startuml
skinparam classAttributeIconSize 0
hide empty members
hide circle

package DataModelFramework {

class DataModel {
   + id: UUID [primaryKey]

   + name: string [unique]

   + instance: int
}

class DataModelChangeHistory {
   + dataModelId: UUID
   + dataModelInstance: int

   + contextEntryType: string   
   + contextId: UUID
   + message: string
}

class DataModelPermission {
   + id: UUID
   + contextEntryType: string -- "DataModel"   
   + contextId: UUID -- DataModel.id
   
   + permission: string
}

}

package GroupManagment {

class DataModelGroup {
   + id: UUID [primaryKey]
   + contextId: UUID [Group.id]
   + contextEntryType: string -- "DataModelGroup"
   
   + type: string -- just for tracing
   
   + validFromInstance: int
   + validToInstance: int
   + dataModelId: UUID
}

class GroupInterest {
   + id: UUID
   + contextId: UUID [Group.id]
   + contextEntryType: string -- "DataModelGroup"

   + controlled: boolean   
   + interestId: UUID
   + interestEntryType: string
   
   + validFromInstance: int
   + validToInstance: int
   + dataModelId: UUID
}

class GroupMembership {
   + id: UUID
   + contextId: UUID [Group.id]
   + contextEntryType: string -- "DataModelGroup"
   
   + userId: UUID
   + validFromInstance: int
   + validToInstance: int
   + dataModelId: UUID
}


}


@enduml
