@startuml
skinparam classAttributeIconSize 0
hide empty members
hide circle

package DataModelFramework {

class DataModel {
   + id: UUID [primaryKey]

   + name: string [unique]

   + instance: int
}

class DataModelChangeHistory {
   + dataModelId: UUID
   + dataModelInstance: int

   + contextEntryType: string   
   + contextId: UUID
   + message: string
}

class DataModelList {
   + id: UUID
   + contextEntryType: string -- "DataModel"   
   + contextId: UUID
   
   + entryType: string -- "User" | "Corporation" | ...
}

}

package UserManagement {

class User {
   + id: UUID [primaryKey]
   + contextId: UUID [DataModel.id]
   + contextEntryType: string -- "DataModel"

   + name: string
}

class Session {
   + id: UUID [primaryKey]
   + contextId: UUID [User.id]
   + contextEntryType: string -- "User"
}

class SessionClient {
   + id: UUID [primaryKey]
   + contextId: UUID [Session.id]
   + contextEntryType: string -- "Session"

   + lastAliveTime: timestamp
   + clientData -- identifying the client
   
   + userId: UUID -- for quicker reference
}

}

package GroupManagment {

class DataModelGroup {
   + id: UUID [primaryKey]
   + contextId: UUID [Group.id]
   + contextEntryType: string -- "DataModelGroup"
   
   + type: string -- just for tracing
   
   + validFromInstance: int
   + validToInstance: int
   + dataModelId: UUID
}

class GroupInterest {
   + id: UUID
   + contextId: UUID [Group.id]
   + contextEntryType: string -- "DataModelGroup"

   + controlled: boolean   
   + interestId: UUID
   + interestEntryType: string
   
   + validFromInstance: int
   + validToInstance: int
   + dataModelId: UUID
}

class GroupMembership {
   + id: UUID
   + contextId: UUID [Group.id]
   + contextEntryType: string -- "DataModelGroup"
   
   + userId: UUID
   + validFromInstance: int
   + validToInstance: int
   + dataModelId: UUID
}


}


@enduml
